name: Generate, lint, test and build

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Installing dependencies
        run: yarn
      - name: Generate AST
        run: yarn --cwd packages/HotDrink-DSL langium:generate
      - name: Lint
        run: yarn --cwd packages/HotDrink-DSL lint
      - name: Run tests
        run: yarn --cwd packages/HotDrink-DSL test
      - name: Build
        run: yarn --cwd packages/HotDrink-DSL build
