name: Generate, lint, test and build

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 12
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Installing dependencies
        run: npm ci
      - name: Generate AST
        run: npm run langium:generate
      - name: Lint
        run: npm run lint
      - name: Run tests
        run: npm test
      - name: Build
        run: npm run build
